export const CATS_GENERATOR_URL = 'https://alyonapianykh.github.io/demo-chrome-extension-rAF-canvas-offscreen/';


export const MESSAGE_TOPICS = {
    // Page <-> Offscreen
    CANVAS_DATA: 'CANVAS_DATA',
    PAGE_READY: 'PAGE_READY',
    REQUEST_CANVAS_DATA: 'REQUEST_CANVAS_DATA',
    TOGGLE_RAF_POLYFILL: 'TOGGLE_STATE_CHANGE',
    OFFSCREEN_READY: 'OFFSCREEN_READY',
    INIT_CATS_IFRAME: 'INIT_CATS_IFRAME',
    DESTROY_CATS_IFRAME: 'DESTROY_CATS_IFRAME',
    REFRESH_CATS_IFRAME: 'REFRESH_CATS_IFRAME',

    // Offscreen <-> Iframe
    OVERRIDE_REQUEST_ANIMATION_FRAME: 'OVERRIDE_REQUEST_ANIMATION_FRAME',
    IFRAME_LOADED: 'IFRAME_LOADED',
    CLEAR_FORCE_OVERRIDE_RAF: 'CLEAR_FORCE_OVERRIDE_RAF',
};
